### DISCUSSION TITLE
Additional Struct Tags

### DISCUSSION THREAD

**Discussion by safaci2000** [stephenafamo/bob#245] [Q&A] [answered]
According to the documentation there is a configuration that allows the user to set "tags.

https://bob.stephenafamo.com/docs/code-generation/configuration/

Given that here's my configuration:

```
psql:
  dsn: "postgres://ht_controller_user:secret@127.0.0.1:5432/funcap_controller?sslmode=disable"
  tags: ["db", "json"]
  wire: true
  wipe: true
  struct_tag_casing: snake
  shared_schema: false
  no_factory: true
  pkgname: "bobs"
  output: "internal/dbmodels/bobs"
  schemas: 
    - funcap
```

I'm seeing the db tag, but also omitting the value still seems to generate that, but the json tag is not being generated.  Is there something I can to to ensure the JSON tag gets generated?

Or is there a list of tags that are supported?

**Comment by stephenafamo** [comment, marked as answer]
The `tags` should be outside the `psql` block. Along with a few other options

```yaml
tags: ["db", "json"]
struct_tag_casing: snake
wipe: true
psql:
  dsn: "postgres://ht_controller_user:secret@127.0.0.1:5432/funcap_controller?sslmode=disable"
  wire: true # I don't think this does anything
  shared_schema: false
  no_factory: true
  pkgname: "bobs"
  output: "internal/dbmodels/bobs"
  schemas: 
    - funcap
```
