### DISCUSSION TITLE
Alias for M2M Relations

### DISCUSSION THREAD

**Discussion by daddz** [stephenafamo/bob#255] [Q&A] [answered]
I'm trying to get bob to generate a custom alias for a m2m relation with a join table.

I couldn't figure out how to get it working from the documentation itself: https://bob.stephenafamo.com/docs/code-generation/configuration#aliases

So with the following tables:
```
team (id)
user (id)
team_owner (team_id, user_id)
```

By default the relation will be called TeamUsers so e.g. `ThenLoadTeamUsers()`.

How do I need to properly set the `aliases` configuration so it would be called e.g. `Owners` aka `ThenLoadOwners()`?

**Comment by stephenafamo** [comment, marked as answer]
In the generated code, you will see the relationship key in a comment in the `modelR` struct. For example:

```go
// videoR is where relationships are stored.
type videoR struct {
	Tags    TagSlice // video_tags.video_tags_tag_id_fkeyvideo_tags.video_tags_video_id_fkey
	Sponsor *Sponsor // videos.videos_sponsor_id_fkey
	User    *User    // videos.videos_user_id_fkey
}
```

Use that in the configuration:

```yaml
aliases:
  team:
    relationships: 
      "video_tags.video_tags_tag_id_fkeyvideo_tags.video_tags_video_id_fkey": "Owner"
```
