### DISCUSSION TITLE
MariaDB not supported ?

### DISCUSSION THREAD

**Discussion by bennyszantar** [stephenafamo/bob#260] [Q&A] [answered]
Hey, 

I wanted to use Bob in my new project which uses MariaDB but unfortunetely I hit roadblock that I cannot bypass.
I've created bobgen.yaml with mysql property.

```yml
mysql:
  dsn: "blabla:blabla@tcp(localhost:3306)/default"
except:
  default.schema_migrations:
```

after running command
```
go run github.com/stephenafamo/bob/gen/bobgen-mysql@latest -c bobgen.yaml
```

im getting error:
```
2024/07/22 16:30:11 unable to fetch table data: unable to load indexes: Error 1054 (42S22): Unknown column 's.expression' in 'field list'
exit status 1
```

This error still happens even if I delete all my tables... Did I misconfigure something or MariaDB is not supported via MYSQL driver ?
