### DISCUSSION TITLE
Many-to-many relationship and pivot columns.

### DISCUSSION THREAD

**Discussion by hiendaovinh** [stephenafamo/bob#261] [Q&A] [answered]
Hi, I'm trying to build a many-to-many relationship by customizing with this
```yaml
relationships:
  users:
    - name: "users-organizations"
      sides:
        - from: "users"
          to: "organization_user"
          columns: [[id, user_id]]
        - from: "organization_user"
          to: "organizations"
          columns: [[organization_id, id]]
```

It works well by returning the related organizations for users but I want to access more fields on the `organization_user` table. Is there anyway to specify extra columns when code-gen the joins? The scan target should be the `OrganizationJoined`, not the original `Organization` struct because it contains more fields from `organization_user` table.
