### DISCUSSION TITLE
Generating a LEFT JOIN via configured relationship

### DISCUSSION THREAD

**Discussion by oliviabarnett** [stephenafamo/bob#275] [General]
Hi! 

I have two tables -- `accounts` and `kyc_infos`, each of which contains an `account_id` and `app_id` field. The `account_id` and `app_id` fields are a unique combination for both tables.

I wanted to do a LEFT JOIN when selecting from the `accounts` table, pulling in the related `kyc_info` row (if present). I followed the preload instructions [here](https://bob.stephenafamo.com/docs/code-generation/relationships#preload), but ended up creating a relationships configuration in my bobgen.yaml that was backwards:

```
relationships:
  accounts:
    - name: "accounts_to_kyc_info"
      never_required: true
      sides:
        - from: "accounts"
          to: "kyc_info"
          columns:
            - [account_id, account_id]
            - [app_id, app_id]
      modify: "from"
```

I had to change it to:
```
  kyc_info:
    - name: "kyc_info_to_accounts"
      never_required: true
      sides:
        - from: "kyc_info"
          to: "accounts"
          columns:
            - [account_id, account_id]
            - [app_id, app_id]
      modify: "from"
```

That allowed this to work:

```
	q := dbmodels.Accounts.Query(
		ctx, r.executor,
		sm.OrderBy(dbmodels.AccountColumns.CreatedAt).Desc(),
		sm.OrderBy(dbmodels.AccountColumns.ID).Desc(),
		// Fetch one more than the limit to check if there's a next page
		sm.Limit(limit+1),

		dbmodels.PreloadAccountKycInfo(),
	)
        dbAccounts, err := q.All()
````

I think it would be super helpful if the configuration file was also included in the example -- its not clear what the relationship between jets and pilots is to me and led to my setting this up incorrectly.

It's also not really clear to me _why_ I have to set up both directions in the first place -- I would kind of think just one defined relationship would work both ways?

**Comment by stephenafamo** [comment]
Can you share a rough schema for these tables, including any primary key or unique constraints?

(PS: I think if you left out the `modify` attribute, the preload would work with the first configuration)

**Reply by oliviabarnett** [reply]
```
CREATE TABLE accounts (
    id VARCHAR(50) PRIMARY KEY, -- KSUID
    account_id VARCHAR(255) NOT NULL CHECK (account_id != ''),
    app_id VARCHAR(255) NOT NULL CHECK (app_id != ''),
   ....
);

CREATE UNIQUE INDEX idx_accounts_app_id_account_id ON accounts (app_id, account_id));

CREATE TABLE kyc_info (
    id VARCHAR(50) PRIMARY KEY, -- KSUID
    account_id VARCHAR(255) NOT NULL CHECK (account_id != ''),
    app_id VARCHAR(255) NOT NULL CHECK (app_id != ''),
    ...
);

CREATE UNIQUE INDEX idx_kyc_info_app_id_account_id ON kyc_info (app_id, account_id));
```

**Reply by oliviabarnett** [reply]
> (PS: I think if you left out the modify attribute, the preload would work with the first configuration)

When I leave out the modify attribute in the first example, I end up with:
```

	q := dbmodels.Accounts.Query(
		ctx, r.executor,
		sm.OrderBy(dbmodels.AccountColumns.CreatedAt).Desc(),
		sm.OrderBy(dbmodels.AccountColumns.ID).Desc(),
		// Fetch one more than the limit to check if there's a next page
		sm.Limit(limit+1),

		dbmodels.PreloadKycInfoAccount(),
	)

	resultOfQuery, _, _ := q.Build()
	r.logger.Info(resultOfQuery)
```

Which gives me this sql:
```
SELECT 
        "accounts_8246"."account_id" AS "accounts_8246.account_id", "accounts_8246"."account_type" AS "accounts_8246.account_type", "accounts_8246"."app_id" AS "accounts_8246.app_id", "accounts_8246"."is_frozen" AS "accounts_8246.is_frozen", "accounts_8246"."frozen_at" AS "accounts_8246.frozen_at", "accounts_8246"."created_at" AS "accounts_8246.created_at", "accounts_8246"."updated_at" AS "accounts_8246.updated_at", "accounts_8246"."id" AS "accounts_8246.id"
        FROM "accounts" AS "accounts"
        LEFT JOIN "accounts" AS "accounts_8246" ON ("kyc_info"."app_id" = "accounts_8246"."app_id") AND ("kyc_info"."account_id" = "accounts_8246"."account_id")
        ORDER BY "accounts"."created_at" DESC, "accounts"."id" DESC
        LIMIT 4
```


The left join here is `LEFT JOIN "accounts"`, which is backwards no?

**Reply by stephenafamo** [reply]
> The left join here is `LEFT JOIN "accounts"`, which is backwards no?

That's because you're using the wrong mod 😂 . Use `dbmodels.PreloadAccountKycInfo()`

**Reply by jalaziz** [reply]
`PreloadAccountKycInfo()` doesn't get generated unless we use the second flipped configuration. However, this is not clear from the docs.

For example, for [this example](https://bob.stephenafamo.com/docs/code-generation/relationships#preload), it seems like the configuration should be similar to:
```
relationships:
  pilots:
    - name: "pilots_to_jets"
      never_required: true
      sides:
        - from: "pilots"
          to: "jets"
          columns:
            - [id, pilot_id]
```

rather than:

```
relationships:
  jets:
    - name: "jets_to_pilots"
      never_required: true
      sides:
        - from: "jets"
          to: "pilots"
          columns:
            - [id, pilot_id]
    - name: "jets_to_copilots"
      never_required: true
      sides:
        - from: "jets"
          to: "pilots"
          columns:
            - [id, copilot_id]
```

Or would we just need to define multiple sides and flip from/to?
