### DISCUSSION TITLE
Factory generation of M2M

### DISCUSSION THREAD

**Discussion by VRmnv** [stephenafamo/bob#404] [Q&A] [answered]
I have M2M relation between two tables, **task** and **task_invoke** via **task_invoke_task_id**.
My relation between them described in config:

```
relationships:
  task_invoke:
    - name: "ti_to_tasks"
      sides:
        - from: "task_invoke"
          to: "task_invoke_task_id"
          columns: [[uuid, task_invoke_id]]
        - from: "task_invoke_task_id"
          to: "task"
          columns: [[task_invoke_id, uuid]]
```

 I'm trying to use factory to generate task and task's task_invokes.

```go
f.NewTask(
factory.TaskMods.AddNewTaskInvokes(2),
).CreateManyOrFail(t.Context(), t, bob.Debug(db), 2)
```

However, in debug log i see only INSERT query for task, and no task invokes inserts.

```
INSERT INTO "task" AS "task" ("uuid",...)
VALUES (DEFAULT, $1, DEFAULT, $2, $3, DEFAULT, DEFAULT, DEFAULT, DEFAULT, $4)
RETURNING "task"."uuid" AS "uuid" ...
```

Am i doing something wrong?
