### DISCUSSION TITLE
How сan I to generate only sql queries without specifying any models?

### DISCUSSION THREAD

**Discussion by errx** [stephenafamo/bob#456] [Q&A] [answered]
Hello, currently I'm only using query generation (sqlc-like) but I can't do this without specifying at least one table with only/except.

```
psql:
  dsn: "postgres://postgres:postgres@localhost:5432/postgres?sslmode=disable"
  driver: github.com/jackc/pgx/v5/stdlib
  except:
    "/^.*/":
  queries:
    - ./queries/
    
```
    
this config doesn't work because of an error: "2025/06/10 16:56:18 no tables found in database"
