### ISSUE TITLE
Use PostgreSQL domain types in type replacements

### ISSUE THREAD

**Issue by plunkettscott** [stephenafamo/bob#10]
We use a custom domain type for IDs in most of our PostgreSQL tables, specifically [this one](https://github.com/modfin/pg-xid). I've not been able to have code generation automatically use the [xid.ID](https://github.com/rs/xid) type, but would really like this to work.

I've tried setting the `db_type` (see below) to be `xid` and `public.xid` (`public.xid` works in sqlc, which we're leaving for bob). I realize this is matching on db_type and not the domain, but I didn't see an option to match the domain. Technically, the actual db_type is `character` as shown in the image below. This is likely why I am getting the code generated models with string-based ID fields.

```yaml
# bobgen.yaml

replacements:
  - match:
      db_type: xid # I've tried public.xid as well
    type: xid.ID
    imports: ['"github.com/rs/xid"']

```

The following is a photo of how the type is represented in postgres using the SQL script I found in the bobgen-psql driver [here](https://github.com/stephenafamo/bob/blob/34f7bff51d5385d42b505726f07ef39269ffec41/gen/bobgen-psql/driver/psql.go#L184). I think this is where the type information is gathered?

![image](https://user-images.githubusercontent.com/4952170/214216177-1a09a915-06bd-4ad7-866a-d3cf0566c0a1.png)

Let me know if you need any further information for this, or if it's not going to be possible.

**Comment by stephenafamo** [comment]
Just released `v0.15.5` to fix this.

Now you should be able to match all those columns with 

```yaml
replacements:
  - match:
      domain_name: xid 
    type: xid.ID
    imports: ['"github.com/rs/xid"']
```

**Comment by plunkettscott** [comment]
Hi @stephenafamo,

I just tested this and it doesn't seem to work. I'm still getting `string` types for the IDs which use this domain. My configuration looks like this:

```yaml
psql:
  dsn: <omitted>
  output: internal/models
  except:
    schema_migrations:
replacements:
  - match:
      domain_name: xid
    type: xid.ID
    imports: ['"github.com/rs/xid"']
```

Am I missing something here?
