### ISSUE TITLE
models folder is always wiped

### ISSUE THREAD

**Issue by HTechHQ** [stephenafamo/bob#201]
**Observed**

When generating the code for a folder that already contains other files: all the other files are deleted.
This continues to happen, even with the `wipe` configuration disabled.

The config file I am using:
```
psql:
  dsn: "postgres://user:pass@host:port/dbname"

  schemas:
    - mySchema
  wipe: false
  output: path/to/models
  uuid_pkg: google
```

**Expected**
The folder contains other files that I need to keep.
The other files should stay available and not be deleted.

**Version**
$ bobgen-psql --version
bobgen-psql version v0.25.0
