### ISSUE TITLE
Cannot load index information for functional indexes

### ISSUE THREAD

**Issue by pcriv** [stephenafamo/bob#244]
After upgrading to `0.28.0` from `0.27.1`, I'm getting the following error when trying to generate code from my schema:

```
unable to fetch table data: unable to load indexes: sql: Scan error on column index 2, name "column_name": converting NULL to string is unsupported
```

**Comment by stephenafamo** [comment]
Can you share more details?

* What driver are you using?
* What does your config look like?
* An example schema to reproduce this

**Comment by pcriv** [comment]
driver: mysql
config:

```yaml
---
mysql:
  dsn: "root:@tcp(localhost:3306)/dname"
  output: internal/dbgen
  pkgname: dbgen
  except:
    schema_migrations:
relationships:
  # hidden
```

About the schema, I cannot share the whole schema, but is there any specific part that you have in mind that could help?
