### ISSUE TITLE
Many-to-many relationship and pivot columns.

### ISSUE THREAD

**Issue by hiendaovinh** [stephenafamo/bob#259]
Hi, I'm trying to build a many-to-many relationship by customizing with this
```yaml
relationships:
  users:
    - name: "users-organizations"
      sides:
        - from: "users"
          to: "organization_user"
          columns: [[id, user_id]]
        - from: "organization_user"
          to: "organizations"
          columns: [[organization_id, id]]
```

It works well by returning the related organizations for users but I want to access more fields on the organization_user table. Is this anyway to specify extra columns when defining this kind of relationship? The scan target should be the OrganizationJoinedStruct, not the original Organization struct because it contains more fields from organization_user table.
