### ISSUE TITLE
Replacements don't Work for Views

### ISSUE THREAD

**Issue by mavolin** [stephenafamo/bob#264]
I have several PostgresSQL views that get correctly generated, but don't get the replacement rules applied, neither through `domain_name` nor more specific rules.

Another problem I encountered, though I suspect this is because of some implementation constraint and not actually a bug: View columns always get generated as `null.Val[T]`, even if they aren't. I'm happy to open a separate issue, if this isn't actually intended.

**Comment by stephenafamo** [comment]
> I have several PostgresSQL views that get correctly generated, but don't get the replacement rules applied, neither through `domain_name` nor more specific rules.

Can you share an example schema and configuration?

> View columns always get generated as `null.Val[T]`

This is a quirk with Postgres.  
When the column data for the view is retrieved, Postgres **always** marks them as nullable.

**Comment by mavolin** [comment]
Sure:
```sql
create table if not exists employees (
    id            bigserial primary key not null,
    name          varchar(128)              not null,
    email         citext                 not null
        constraint employee_email_unique unique,
    -- ...
);

create or replace view employee_overview as
select id, name, email from employees;
```

with

```yaml
psql: # ...

types:
  domain.EmployeeID:
    imports: # ...

replacements:
    - tables: [employees, employee_overview]
      match: {name: id}
      replace: domain.EmployeeID
```

generates

```go
type EmployeeOverview struct {
	ID    null.Val[int64]  `db:"id" `
	Name  null.Val[string] `db:"name" `
	Email null.Val[string] `db:"email" `
}
```

`Employee` generates correctly:
```go
type Employee struct {
	ID           domain.EmployeeID             `db:"id,pk" `
	Name         string                        `db:"name" `
	Email        string                        `db:"email" `
	// ...

	R employeeR `db:"-" `
}
```

bobgen-psql is on v0.28.1.

**Comment by mavolin** [comment]
Another example with a `domain_name` rule:

```sql
create domain product_id as bigint;
create domain customer_id as bigint;

create table if not exists claims (
    id                  bigserial primary key not null,
    -- ...
    product_id          product_id            not null references products (id),
    -- ...
    customer_id         customer_id           not null references customers (id),
    -- ...
);

create or replace view claim_overview as
select claims.id,
       claims.completed_at,
       product_id     as product_id,
       products.name  as product_name,
       customer_id    as customer_id,
       customers.name as customer_name
from claims
         inner join products on claims.product_id = products.id
         inner join customers on claims.customer_id = customers.id;
```

with

```yaml
psql: # ...

types:
  domain.CustomerID: # ...
  domain.ProductID: #...

replacements:
  - match: {domain_name: customer_id}
    replace: domain.CustomerID
  - match: {domain_name: product_id}
    replace: domain.ProductID
```

generates:
```go
type ClaimOverview struct {
	ID           null.Val[int64]     `db:"id" `
	CompletedAt  null.Val[time.Time] `db:"completed_at" `
	ProductID    null.Val[int64]     `db:"product_id" `
	ProductName  null.Val[string]    `db:"product_name" `
	CustomerID   null.Val[int64]     `db:"customer_id" `
	CustomerName null.Val[string]    `db:"customer_name" `
}
```
