### ISSUE TITLE
sqlite generated code is missing the Query method.

### ISSUE THREAD

**Issue by sixilli** [stephenafamo/bob#279]
The documentation showed that I should be able to do something like `models.Cameras.Query(...)`, but it appears that the SQLite code generation produced a bad output file.

Command ran
`go run github.com/stephenafamo/bob/gen/bobgen-sqlite@latest -c ./config/bobgen.yaml`

bobgen.yml
```yaml
sqlite:
  dsn: "dvr.db"
  output: "./gen/sql/dvrsql"
  pkgname: "dvrsql"
```

table definition
```sql
CREATE TABLE cameras (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    camera_id INTEGER NOT NULL,
    camera_name TEXT NOT NULL,
    audio_codec TEXT,
    video_codec TEXT,
    resolution TEXT,
    frames_per_second TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
```

issues with ./gen/sql/dvrsql/camera.go

The generated code has a naming collision, one of these two `Cameras` needs to be changed.

```go
// Cameras is an object representing the database table.
type Cameras struct {
	ID              int32            `db:"id,pk" `
	CameraID        int32            `db:"camera_id" `
	CameraName      string           `db:"camera_name" `
	AudioCodec      null.Val[string] `db:"audio_codec" `
	VideoCodec      null.Val[string] `db:"video_codec" `
	Resolution      null.Val[string] `db:"resolution" `
	FramesPerSecond null.Val[string] `db:"frames_per_second" `
	CreatedAt       null.Val[string] `db:"created_at" `
	UpdatedAt       null.Val[string] `db:"updated_at" `
}

var Cameras = sqlite.NewTablex[*Cameras, CamerasSlice, *CamerasSetter]("", "cameras")
```

For now I manually modified the generated code, but since this is a toy project it's not exactly running yet. But I would imagine that everything works after the manual changes. I'll update the issue if I find anything else.

**Comment by stephenafamo** [comment]
The issue is that despite best effort, it cannot determine the singular/pluaral of `cameras`. This can be fixed using the aliases configuration:

```yaml
aliases:
  cameras:
    up_plural: "Cameras"
    up_singular: "Camera"
    down_plural: "cameras"
    down_singular: "camera"
```
