### ISSUE TITLE
bug struct name redeclared

### ISSUE THREAD

**Issue by gocpicnic** [stephenafamo/bob#387]
I create a sqlite.db :example.db .use this bash:
```bash
touch example.db
sqlite3 example.db <<EOF
CREATE TABLE cameras (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  email TEXT UNIQUE NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO cameras (name, email) VALUES
('Alice', 'alice@example.com'),
('Bob', 'bob@example.com');
EOF
```
and then, i use this example.yaml:
```yaml
sqlite:
  dsn: "./storage/example.db"
  driver_name: "modernc.org/sqlite"  
  output: "./internal/entity1"                  
  pkgname: "entity1"       

tags: ["json", "yaml"]
```
run 
`go run github.com/stephenafamo/bob/gen/bobgen-sqlite@latest -c ./storage/example.yaml`
I  get cameras.bob.go .Some code like this:
```go
// Cameras is an object representing the database table.
type Cameras struct {
	ID        int32               `db:"id,pk" json:"id" yaml:"id"`
	Name      string              `db:"name" json:"name" yaml:"name"`
	Email     string              `db:"email" json:"email" yaml:"email"`
	CreatedAt null.Val[time.Time] `db:"created_at" json:"created_at" yaml:"created_at"`
}

// CamerasSlice is an alias for a slice of pointers to Cameras.
// This should almost always be used instead of []*Cameras.
type CamerasSlice []*Cameras

// Cameras contains methods to work with the cameras table
var Cameras = sqlite.NewTablex[*Cameras, CamerasSlice, *CamerasSetter]("", "cameras")
```

so you can see the `type  Cameras struct` and `var Cameras`,they are same .

I got error `Cameras redeclared in this block (see details)`

**Comment by stephenafamo** [comment]
The issue is that Bob is unable to tell the singular an plural of Cameras. Try adding this to your config

```yaml
# Although team_names works fine without configuration, we use it here for illustrative purposes
aliases:
  cameras:
    up_singular: "Camera"
    down_singular: "camera"
```
