### ISSUE TITLE
Ignore down sql scripts while using sql driver

### ISSUE THREAD

**Issue by mfechner** [stephenafamo/bob#393]
I have a project that is using [go-migrate](https://github.com/golang-migrate/migrate) to apply required migrations to a mysql database.
It uses filenames that end with `.up.sql` to apply migrations and `.down.sql` to undo the migration.

If I now configure `bob.yaml` with:
```
# Generate from migration files is not supported for mysql yet
sql:
  dialect: psql
  dir: db/migrations
  output: models
  pkgname: models
```
it also tries to execute the `*.down.sql` script which will cause problems.

I found in the documentation only how to exclude tables, but not how to exclude file patterns or to define a glob for files that should be included like `*.up.sql`.

Is there something existing, I maybe miss?
