### ISSUE TITLE
Missing schema value for psql

### ISSUE THREAD

**Issue by miniscruff** [stephenafamo/bob#40]
When using schemas in postgres it seems the schema value is missing from the generated output.

```yaml
psql:
  schemas: ["xyz"]
  output: dbbob
  pkgname: dbbob
```

Where I believe this value is missing:
```go
// what is generated
var ImagesTable = psql.NewTablex[*Image, ImageSlice, *ImageSetter]("", "image")

// what I believe it should be
var ImagesTable = psql.NewTablex[*Image, ImageSlice, *ImageSetter]("xyz", "image")
```
