### ISSUE TITLE
Cross schema code generation broken after upgrade

### ISSUE THREAD

**Issue by stannok** [stephenafamo/bob#443]
After upgrading from version 0.34.2 to 0.37.0 the code generation when using multiple schemas no longer works. I've done all the sql.Null migrations. 

The Factory generation fails looking for a table without the schema name.  For example for a table "users" in schema "core" it throws:

`unable to generate output: execute templates: failed to execute template: 03_create.go.tpl: template: 03_create.go.tpl:171:27: executing "03_create.go.tpl" at <$.Tables.ColumnAssigner>: error calling ColumnAssigner: could not find table name: users`

When running a query on the users table it generates a incorrect query for the Postgresql dialect:

```
user, err := models.CoreUsers.Query(
	models.SelectWhere.BaseUsers.Email.EQ(email),
).One(ctx, db)
if err != nil {
	if errors.Is(err, sql.ErrNoRows) {
		return nil, errors.New("user not found")
	}
	return nil, err
}
```

```
SELECT "core"."users"."id" AS "id", "core"."users"."first_name" AS "first_name", "core"."users"."last_name" AS "last_name", "core"."users"."email" AS "email", "core"."users"."created_at" AS "created_at", "core"."users"."updated_at" AS "updated_at"
FROM "core"."users" AS "core.users"
WHERE ("core.users"."email" = 'john.doe@email.com');
```

I guess it should generate the alias "core.users"."id" in stead of "core"."user"."id" for column names?

### Config file

```
no_factory: true (When setting this propt to true the generation passes, but the queries are generated incorrectly.)

psql:
  dsn: 'postgres://postgres:postgres@localhost:5432/db_name?sslmode=disable'
  driver: 'github.com/jackc/pgx/v5/stdlib'
  schemas: ['public', 'base'']
  shared_schema: 'public'
  output: 'models'
  pkgname: 'models'
  uuid_pkg: 'google'
  concurrency: 10
  # only:
  except:
    public.migrations:
```

### Environment

Golang version: 1.24.1 Darwin/arm
Bob version: 0.37.0 (for generation and go.mod)
Dialect: Postgreql (PGX driver)

Please let me know if I'm missing something.
