### ISSUE TITLE
Code generation with camelCase table names in PostgreSQL

### ISSUE THREAD

**Issue by matyushen** [stephenafamo/bob#448]
I'm trying to use Bob to generate models from a PostgreSQL database that has tables with `camelCase` names (e.g., `"offerSecondPromotions"`). However, the code generation fails with:

```  unable to fetch table data: unable to load comments: pq: relation
  "public.offersecondpromotions" does not exist
```

It appears Bob is querying for lowercase table names when the actual table is camelCase. In PostgreSQL, camelCase identifiers need to be double-quoted to preserve case.

Configuration:

```yaml
  output: "./internal/generated"
  pkgname: "models"
  schema:
    - "public"
  psql:
    dsn: "postgres://user:pass@localhost:5432/db?sslmode=disable"
```

Is there a way to configure Bob to handle camelCase table names, or does Bob require snake_case identifiers? Or am I simply missing how to properly configure this?

Environment: Bob v0.38.0, PostgreSQL 17.4
