### ISSUE TITLE
Allow column comment for replacement matching

### ISSUE THREAD

**Issue by plunkettscott** [stephenafamo/bob#69]
It would be very useful if a comment could be used to match replacement types. I tend to comment the application type for my own sanity when dealing with foreign keys and ID columns (like: `xid`) when it's an xid ID.

I tried to add the following match hoping it would work, but it did not. I'm trying to avoid having a ton of replacement matchers in my config in order to unmarshal ID types everywhere (matching by column/table names), but it's sort of what I am having to do right now (otherwise I have to handle it in my code, which defeats the purpose of codegen imho).

```yaml
replacements:
  - match:
      comment: xid
    replace:
      type: xid.ID
      imports: ['"github.com/rs/xid"']
```

Any chance this could be supported? It would be immensely helpful for some cases like this, especially when working with things like MySQL which do not support domain types.

For this use case, an exact match of the string is perfectly acceptable.
