### ISSUE TITLE
SQLite except config generating models

### ISSUE THREAD

**Issue by delaneyj** [stephenafamo/bob#70]
```yaml
# bobgen.yaml
wipe: true
sqlite:
  dsn: "foo.db"
  except:
    migrations:
```

Also have tried `main.migrations` but migrations still getting generated
